image: vopay/yapov:latest

pipelines:
  default:
    - step:
        caches:
          - node
        name: 'Build'
        script:
          - npm i
          - npm run build
    - parallel:
      - step:
          caches:
            - node
          name: 'Test'
          script:
            - echo "No testing yet..."
      - step:
          caches:
            - node
          name: 'Lint'
          script:
            - npm run lint.checkstyle
            - pipe: atlassian/checkstyle-report:0.3.1
              variables:
                # CHECKSTYLE_RESULT_PATTERN: '<string>' # Optional.
                # CHECKSTYLE_REPORT_ID: '<string>'      # Optional.
                REPORT_FAIL_SEVERITY: 'error'       # Optional.
      - step:
          caches:
            - node
          name: 'Security scan'
          trigger: manual
          script:
            - echo "Security scanning..."
            - pipe: snyk/snyk-scan:0.5.2
              variables:
                SNYK_TOKEN: $SNYK_TOKEN
                LANGUAGE: "npm" # Required unless SNYK_TEST_JSON_INPUT is set
                # IMAGE_NAME: "<string>" # Only required if LANGUAGE set to "docker"
                CODE_INSIGHTS_RESULTS: "True" # Optional.
                # SNYK_TEST_JSON_INPUT: "<string>" # Optional. The filename or path of a JSON file containing the output from running a test with the Snyk CLI (with json output option).
                # PROTECT: "<boolean>" # Optional.
                DONT_BREAK_BUILD: "True" # Optional.
                MONITOR: "True" # Optional.
                # SEVERITY_THRESHOLD: "<low|medium|high|critical>" # Optional.
                ORGANIZATION: "VoPay" # Optional.
                PROJECT_FOLDER: "_site" # Optional.
                # TARGET_FILE: "<string>" # Optional.
                # EXTRA_ARGS: "<string>" # Optional.
                DEBUG: "True" # Optional.

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        caches:
          - node
        name: 'Deployment to Staging'
        deployment: staging
        trigger: 'manual'
        script:
          - echo "Uploading to AWS Amplify..."
        after-script:
          - echo "Querying AWS Amplify for the URL..."
          - if test -f result.svg; then rm result.svg; fi  # Remove the previous result
          - echo "Checking if AMPLIFY_URL is set and exit code was zero"
          - export SLK_MSG="Deployed to AWS Amplify (commit ${BITBUCKET_COMMIT}"
          - if [[ $BITBUCKET_EXIT_CODE -eq 0 && -z "$AMPLIFY_URL" ]]; then ln pass.svg result.svg; export SLK_MSG="$SLK_MSG url $AMPLIFY_URL)"; else ln fail.svg result.svg; export SLK_MSG="$SLK_MSG)"; fi
          - pipe: atlassian/slack-notify:2.0.0
            variables:
              WEBHOOK_URL: 'https://hooks.slack.com/services/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'
              PRETEXT: 'Docs Staging'
              MESSAGE: "$SLK_MSG"
              PAYLOAD_FILE: 'result.svg' # Optional.
              DEBUG: 'True' # Optional.
    - step:
        caches:
          - node
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "No production deploy yet"
definitions:
  caches:
    bundler: vendor/bundle
